# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from p5/CommandRobotRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import p5.msg

class CommandRobotRequest(genpy.Message):
  _md5sum = "e389a3de6f2b8baf5e2e65f0d3ed16a7"
  _type = "p5/CommandRobotRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """State state
Action action

================================================================================
MSG: p5/State
int8 location
float64[5] distribution

================================================================================
MSG: p5/Action
int8 STOP = -1
int8 SENSE = 0
int8 MOVE1 = 1
int8 MOVE2 = 2
int8 MOVE3 = 3
int8 MOVE4 = 4
int8 MOVE5 = 5

int8 name
"""
  __slots__ = ['state','action']
  _slot_types = ['p5/State','p5/Action']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       state,action

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CommandRobotRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.state is None:
        self.state = p5.msg.State()
      if self.action is None:
        self.action = p5.msg.Action()
    else:
      self.state = p5.msg.State()
      self.action = p5.msg.Action()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_b().pack(self.state.location))
      buff.write(_get_struct_5d().pack(*self.state.distribution))
      buff.write(_get_struct_b().pack(self.action.name))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.state is None:
        self.state = p5.msg.State()
      if self.action is None:
        self.action = p5.msg.Action()
      end = 0
      start = end
      end += 1
      (self.state.location,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 40
      self.state.distribution = _get_struct_5d().unpack(str[start:end])
      start = end
      end += 1
      (self.action.name,) = _get_struct_b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_b().pack(self.state.location))
      buff.write(self.state.distribution.tostring())
      buff.write(_get_struct_b().pack(self.action.name))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.state is None:
        self.state = p5.msg.State()
      if self.action is None:
        self.action = p5.msg.Action()
      end = 0
      start = end
      end += 1
      (self.state.location,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 40
      self.state.distribution = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=5)
      start = end
      end += 1
      (self.action.name,) = _get_struct_b().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d = None
def _get_struct_5d():
    global _struct_5d
    if _struct_5d is None:
        _struct_5d = struct.Struct("<5d")
    return _struct_5d
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from p5/CommandRobotResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import p5.msg

class CommandRobotResponse(genpy.Message):
  _md5sum = "c3a5ead86a2476c26428873b534e0e92"
  _type = "p5/CommandRobotResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """State next_state


================================================================================
MSG: p5/State
int8 location
float64[5] distribution
"""
  __slots__ = ['next_state']
  _slot_types = ['p5/State']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       next_state

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(CommandRobotResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.next_state is None:
        self.next_state = p5.msg.State()
    else:
      self.next_state = p5.msg.State()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_b().pack(self.next_state.location))
      buff.write(_get_struct_5d().pack(*self.next_state.distribution))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.next_state is None:
        self.next_state = p5.msg.State()
      end = 0
      start = end
      end += 1
      (self.next_state.location,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 40
      self.next_state.distribution = _get_struct_5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_b().pack(self.next_state.location))
      buff.write(self.next_state.distribution.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.next_state is None:
        self.next_state = p5.msg.State()
      end = 0
      start = end
      end += 1
      (self.next_state.location,) = _get_struct_b().unpack(str[start:end])
      start = end
      end += 40
      self.next_state.distribution = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=5)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5d = None
def _get_struct_5d():
    global _struct_5d
    if _struct_5d is None:
        _struct_5d = struct.Struct("<5d")
    return _struct_5d
_struct_b = None
def _get_struct_b():
    global _struct_b
    if _struct_b is None:
        _struct_b = struct.Struct("<b")
    return _struct_b
class CommandRobot(object):
  _type          = 'p5/CommandRobot'
  _md5sum = '744a27ef9dbc5d25c1c0c348dc1c1401'
  _request_class  = CommandRobotRequest
  _response_class = CommandRobotResponse
