// Generated by gencpp from file p1/Draw.msg
// DO NOT EDIT!


#ifndef P1_MESSAGE_DRAW_H
#define P1_MESSAGE_DRAW_H

#include <ros/service_traits.h>


#include <p1/DrawRequest.h>
#include <p1/DrawResponse.h>


namespace p1
{

struct Draw
{

typedef DrawRequest Request;
typedef DrawResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Draw
} // namespace p1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p1::Draw > {
  static const char* value()
  {
    return "d74afb0d9a5429b7e16cd23054d13ebb";
  }

  static const char* value(const ::p1::Draw&) { return value(); }
};

template<>
struct DataType< ::p1::Draw > {
  static const char* value()
  {
    return "p1/Draw";
  }

  static const char* value(const ::p1::Draw&) { return value(); }
};


// service_traits::MD5Sum< ::p1::DrawRequest> should match 
// service_traits::MD5Sum< ::p1::Draw > 
template<>
struct MD5Sum< ::p1::DrawRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p1::Draw >::value();
  }
  static const char* value(const ::p1::DrawRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p1::DrawRequest> should match 
// service_traits::DataType< ::p1::Draw > 
template<>
struct DataType< ::p1::DrawRequest>
{
  static const char* value()
  {
    return DataType< ::p1::Draw >::value();
  }
  static const char* value(const ::p1::DrawRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p1::DrawResponse> should match 
// service_traits::MD5Sum< ::p1::Draw > 
template<>
struct MD5Sum< ::p1::DrawResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p1::Draw >::value();
  }
  static const char* value(const ::p1::DrawResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p1::DrawResponse> should match 
// service_traits::DataType< ::p1::Draw > 
template<>
struct DataType< ::p1::DrawResponse>
{
  static const char* value()
  {
    return DataType< ::p1::Draw >::value();
  }
  static const char* value(const ::p1::DrawResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P1_MESSAGE_DRAW_H
