// Generated by gencpp from file p1/DrawRequest.msg
// DO NOT EDIT!


#ifndef P1_MESSAGE_DRAWREQUEST_H
#define P1_MESSAGE_DRAWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace p1
{
template <class ContainerAllocator>
struct DrawRequest_
{
  typedef DrawRequest_<ContainerAllocator> Type;

  DrawRequest_()
    : count(0.0)
    , rotate(false)  {
    }
  DrawRequest_(const ContainerAllocator& _alloc)
    : count(0.0)
    , rotate(false)  {
  (void)_alloc;
    }



   typedef double _count_type;
  _count_type count;

   typedef uint8_t _rotate_type;
  _rotate_type rotate;





  typedef boost::shared_ptr< ::p1::DrawRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p1::DrawRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DrawRequest_

typedef ::p1::DrawRequest_<std::allocator<void> > DrawRequest;

typedef boost::shared_ptr< ::p1::DrawRequest > DrawRequestPtr;
typedef boost::shared_ptr< ::p1::DrawRequest const> DrawRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p1::DrawRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p1::DrawRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'turtlesim': ['/opt/ros/melodic/share/turtlesim/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p1::DrawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p1::DrawRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p1::DrawRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p1::DrawRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p1::DrawRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p1::DrawRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p1::DrawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "88fab6d93a63caa50357242686459b3c";
  }

  static const char* value(const ::p1::DrawRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x88fab6d93a63caa5ULL;
  static const uint64_t static_value2 = 0x0357242686459b3cULL;
};

template<class ContainerAllocator>
struct DataType< ::p1::DrawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p1/DrawRequest";
  }

  static const char* value(const ::p1::DrawRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p1::DrawRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 count\n\
bool rotate\n\
\n\
";
  }

  static const char* value(const ::p1::DrawRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p1::DrawRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.count);
      stream.next(m.rotate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DrawRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p1::DrawRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p1::DrawRequest_<ContainerAllocator>& v)
  {
    s << indent << "count: ";
    Printer<double>::stream(s, indent + "  ", v.count);
    s << indent << "rotate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.rotate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P1_MESSAGE_DRAWREQUEST_H
