(cl:defpackage p3-srv
  (:use )
  (:export
   "JACSTRING"
   "<JACSTRING-REQUEST>"
   "JACSTRING-REQUEST"
   "<JACSTRING-RESPONSE>"
   "JACSTRING-RESPONSE"
   "PROBLEM1"
   "<PROBLEM1-REQUEST>"
   "PROBLEM1-REQUEST"
   "<PROBLEM1-RESPONSE>"
   "PROBLEM1-RESPONSE"
   "PROBLEM2"
   "<PROBLEM2-REQUEST>"
   "PROBLEM2-REQUEST"
   "<PROBLEM2-RESPONSE>"
   "PROBLEM2-RESPONSE"
   "PROBLEM3A"
   "<PROBLEM3A-REQUEST>"
   "PROBLEM3A-REQUEST"
   "<PROBLEM3A-RESPONSE>"
   "PROBLEM3A-RESPONSE"
  ))

