// Generated by gencpp from file p5/ActionEffect.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_ACTIONEFFECT_H
#define P5_MESSAGE_ACTIONEFFECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <p5/State.h>

namespace p5
{
template <class ContainerAllocator>
struct ActionEffect_
{
  typedef ActionEffect_<ContainerAllocator> Type;

  ActionEffect_()
    : next_state()
    , probability(0.0)
    , reward(0.0)  {
    }
  ActionEffect_(const ContainerAllocator& _alloc)
    : next_state(_alloc)
    , probability(0.0)
    , reward(0.0)  {
  (void)_alloc;
    }



   typedef  ::p5::State_<ContainerAllocator>  _next_state_type;
  _next_state_type next_state;

   typedef double _probability_type;
  _probability_type probability;

   typedef double _reward_type;
  _reward_type reward;





  typedef boost::shared_ptr< ::p5::ActionEffect_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p5::ActionEffect_<ContainerAllocator> const> ConstPtr;

}; // struct ActionEffect_

typedef ::p5::ActionEffect_<std::allocator<void> > ActionEffect;

typedef boost::shared_ptr< ::p5::ActionEffect > ActionEffectPtr;
typedef boost::shared_ptr< ::p5::ActionEffect const> ActionEffectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p5::ActionEffect_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p5::ActionEffect_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p5': ['/home/cs4750/catkin_ws/src/p5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p5::ActionEffect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p5::ActionEffect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::ActionEffect_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::ActionEffect_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::ActionEffect_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::ActionEffect_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p5::ActionEffect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "389fa51769ae72e234321be7110c4f63";
  }

  static const char* value(const ::p5::ActionEffect_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x389fa51769ae72e2ULL;
  static const uint64_t static_value2 = 0x34321be7110c4f63ULL;
};

template<class ContainerAllocator>
struct DataType< ::p5::ActionEffect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p5/ActionEffect";
  }

  static const char* value(const ::p5::ActionEffect_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p5::ActionEffect_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State next_state	# the state this action is transitioning to\n\
float64 probability	# the probability of that transition occurring in this state\n\
float64 reward		# the reward resulting from this transition\n\
\n\
================================================================================\n\
MSG: p5/State\n\
int8 location\n\
float64[5] distribution\n\
";
  }

  static const char* value(const ::p5::ActionEffect_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p5::ActionEffect_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.next_state);
      stream.next(m.probability);
      stream.next(m.reward);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ActionEffect_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p5::ActionEffect_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p5::ActionEffect_<ContainerAllocator>& v)
  {
    s << indent << "next_state: ";
    s << std::endl;
    Printer< ::p5::State_<ContainerAllocator> >::stream(s, indent + "  ", v.next_state);
    s << indent << "probability: ";
    Printer<double>::stream(s, indent + "  ", v.probability);
    s << indent << "reward: ";
    Printer<double>::stream(s, indent + "  ", v.reward);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P5_MESSAGE_ACTIONEFFECT_H
