// Generated by gencpp from file p5/ChooseAction.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_CHOOSEACTION_H
#define P5_MESSAGE_CHOOSEACTION_H

#include <ros/service_traits.h>


#include <p5/ChooseActionRequest.h>
#include <p5/ChooseActionResponse.h>


namespace p5
{

struct ChooseAction
{

typedef ChooseActionRequest Request;
typedef ChooseActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChooseAction
} // namespace p5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p5::ChooseAction > {
  static const char* value()
  {
    return "0b388a89a907fef764c8117a010b7015";
  }

  static const char* value(const ::p5::ChooseAction&) { return value(); }
};

template<>
struct DataType< ::p5::ChooseAction > {
  static const char* value()
  {
    return "p5/ChooseAction";
  }

  static const char* value(const ::p5::ChooseAction&) { return value(); }
};


// service_traits::MD5Sum< ::p5::ChooseActionRequest> should match 
// service_traits::MD5Sum< ::p5::ChooseAction > 
template<>
struct MD5Sum< ::p5::ChooseActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p5::ChooseAction >::value();
  }
  static const char* value(const ::p5::ChooseActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::ChooseActionRequest> should match 
// service_traits::DataType< ::p5::ChooseAction > 
template<>
struct DataType< ::p5::ChooseActionRequest>
{
  static const char* value()
  {
    return DataType< ::p5::ChooseAction >::value();
  }
  static const char* value(const ::p5::ChooseActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p5::ChooseActionResponse> should match 
// service_traits::MD5Sum< ::p5::ChooseAction > 
template<>
struct MD5Sum< ::p5::ChooseActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p5::ChooseAction >::value();
  }
  static const char* value(const ::p5::ChooseActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::ChooseActionResponse> should match 
// service_traits::DataType< ::p5::ChooseAction > 
template<>
struct DataType< ::p5::ChooseActionResponse>
{
  static const char* value()
  {
    return DataType< ::p5::ChooseAction >::value();
  }
  static const char* value(const ::p5::ChooseActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P5_MESSAGE_CHOOSEACTION_H
