// Generated by gencpp from file p5/ClosestPointPathRequest.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_CLOSESTPOINTPATHREQUEST_H
#define P5_MESSAGE_CLOSESTPOINTPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace p5
{
template <class ContainerAllocator>
struct ClosestPointPathRequest_
{
  typedef ClosestPointPathRequest_<ContainerAllocator> Type;

  ClosestPointPathRequest_()
    : robot_position()
    , path()  {
    }
  ClosestPointPathRequest_(const ContainerAllocator& _alloc)
    : robot_position(_alloc)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _robot_position_type;
  _robot_position_type robot_position;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::p5::ClosestPointPathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p5::ClosestPointPathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ClosestPointPathRequest_

typedef ::p5::ClosestPointPathRequest_<std::allocator<void> > ClosestPointPathRequest;

typedef boost::shared_ptr< ::p5::ClosestPointPathRequest > ClosestPointPathRequestPtr;
typedef boost::shared_ptr< ::p5::ClosestPointPathRequest const> ClosestPointPathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p5::ClosestPointPathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p5::ClosestPointPathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p5': ['/home/cs4750/catkin_ws/src/p5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p5::ClosestPointPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p5::ClosestPointPathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::ClosestPointPathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::ClosestPointPathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::ClosestPointPathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::ClosestPointPathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p5::ClosestPointPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "69132ef72062833147deff265b0303b6";
  }

  static const char* value(const ::p5::ClosestPointPathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x69132ef720628331ULL;
  static const uint64_t static_value2 = 0x47deff265b0303b6ULL;
};

template<class ContainerAllocator>
struct DataType< ::p5::ClosestPointPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p5/ClosestPointPathRequest";
  }

  static const char* value(const ::p5::ClosestPointPathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p5::ClosestPointPathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point robot_position\n\
geometry_msgs/Point[] path\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::p5::ClosestPointPathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p5::ClosestPointPathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_position);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ClosestPointPathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p5::ClosestPointPathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p5::ClosestPointPathRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.robot_position);
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // P5_MESSAGE_CLOSESTPOINTPATHREQUEST_H
