// Generated by gencpp from file p5/ClosestPointPath.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_CLOSESTPOINTPATH_H
#define P5_MESSAGE_CLOSESTPOINTPATH_H

#include <ros/service_traits.h>


#include <p5/ClosestPointPathRequest.h>
#include <p5/ClosestPointPathResponse.h>


namespace p5
{

struct ClosestPointPath
{

typedef ClosestPointPathRequest Request;
typedef ClosestPointPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClosestPointPath
} // namespace p5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p5::ClosestPointPath > {
  static const char* value()
  {
    return "a4eb7978da311d6bb271e96cc9f6a8e7";
  }

  static const char* value(const ::p5::ClosestPointPath&) { return value(); }
};

template<>
struct DataType< ::p5::ClosestPointPath > {
  static const char* value()
  {
    return "p5/ClosestPointPath";
  }

  static const char* value(const ::p5::ClosestPointPath&) { return value(); }
};


// service_traits::MD5Sum< ::p5::ClosestPointPathRequest> should match 
// service_traits::MD5Sum< ::p5::ClosestPointPath > 
template<>
struct MD5Sum< ::p5::ClosestPointPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p5::ClosestPointPath >::value();
  }
  static const char* value(const ::p5::ClosestPointPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::ClosestPointPathRequest> should match 
// service_traits::DataType< ::p5::ClosestPointPath > 
template<>
struct DataType< ::p5::ClosestPointPathRequest>
{
  static const char* value()
  {
    return DataType< ::p5::ClosestPointPath >::value();
  }
  static const char* value(const ::p5::ClosestPointPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p5::ClosestPointPathResponse> should match 
// service_traits::MD5Sum< ::p5::ClosestPointPath > 
template<>
struct MD5Sum< ::p5::ClosestPointPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p5::ClosestPointPath >::value();
  }
  static const char* value(const ::p5::ClosestPointPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::ClosestPointPathResponse> should match 
// service_traits::DataType< ::p5::ClosestPointPath > 
template<>
struct DataType< ::p5::ClosestPointPathResponse>
{
  static const char* value()
  {
    return DataType< ::p5::ClosestPointPath >::value();
  }
  static const char* value(const ::p5::ClosestPointPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P5_MESSAGE_CLOSESTPOINTPATH_H
