// Generated by gencpp from file p5/CommandRobotRequest.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_COMMANDROBOTREQUEST_H
#define P5_MESSAGE_COMMANDROBOTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <p5/State.h>
#include <p5/Action.h>

namespace p5
{
template <class ContainerAllocator>
struct CommandRobotRequest_
{
  typedef CommandRobotRequest_<ContainerAllocator> Type;

  CommandRobotRequest_()
    : state()
    , action()  {
    }
  CommandRobotRequest_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef  ::p5::State_<ContainerAllocator>  _state_type;
  _state_type state;

   typedef  ::p5::Action_<ContainerAllocator>  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::p5::CommandRobotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p5::CommandRobotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CommandRobotRequest_

typedef ::p5::CommandRobotRequest_<std::allocator<void> > CommandRobotRequest;

typedef boost::shared_ptr< ::p5::CommandRobotRequest > CommandRobotRequestPtr;
typedef boost::shared_ptr< ::p5::CommandRobotRequest const> CommandRobotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p5::CommandRobotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p5::CommandRobotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p5': ['/home/cs4750/catkin_ws/src/p5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p5::CommandRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p5::CommandRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::CommandRobotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::CommandRobotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::CommandRobotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::CommandRobotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p5::CommandRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e389a3de6f2b8baf5e2e65f0d3ed16a7";
  }

  static const char* value(const ::p5::CommandRobotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe389a3de6f2b8bafULL;
  static const uint64_t static_value2 = 0x5e2e65f0d3ed16a7ULL;
};

template<class ContainerAllocator>
struct DataType< ::p5::CommandRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p5/CommandRobotRequest";
  }

  static const char* value(const ::p5::CommandRobotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p5::CommandRobotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State state\n\
Action action\n\
\n\
================================================================================\n\
MSG: p5/State\n\
int8 location\n\
float64[5] distribution\n\
\n\
================================================================================\n\
MSG: p5/Action\n\
int8 STOP = -1\n\
int8 SENSE = 0\n\
int8 MOVE1 = 1\n\
int8 MOVE2 = 2\n\
int8 MOVE3 = 3\n\
int8 MOVE4 = 4\n\
int8 MOVE5 = 5\n\
\n\
int8 name\n\
";
  }

  static const char* value(const ::p5::CommandRobotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p5::CommandRobotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandRobotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p5::CommandRobotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p5::CommandRobotRequest_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::p5::State_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
    s << indent << "action: ";
    s << std::endl;
    Printer< ::p5::Action_<ContainerAllocator> >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P5_MESSAGE_COMMANDROBOTREQUEST_H
