// Generated by gencpp from file p5/CommandRobotResponse.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_COMMANDROBOTRESPONSE_H
#define P5_MESSAGE_COMMANDROBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <p5/State.h>

namespace p5
{
template <class ContainerAllocator>
struct CommandRobotResponse_
{
  typedef CommandRobotResponse_<ContainerAllocator> Type;

  CommandRobotResponse_()
    : next_state()  {
    }
  CommandRobotResponse_(const ContainerAllocator& _alloc)
    : next_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::p5::State_<ContainerAllocator>  _next_state_type;
  _next_state_type next_state;





  typedef boost::shared_ptr< ::p5::CommandRobotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p5::CommandRobotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct CommandRobotResponse_

typedef ::p5::CommandRobotResponse_<std::allocator<void> > CommandRobotResponse;

typedef boost::shared_ptr< ::p5::CommandRobotResponse > CommandRobotResponsePtr;
typedef boost::shared_ptr< ::p5::CommandRobotResponse const> CommandRobotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p5::CommandRobotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p5::CommandRobotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p5': ['/home/cs4750/catkin_ws/src/p5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p5::CommandRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p5::CommandRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::CommandRobotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::CommandRobotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::CommandRobotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::CommandRobotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p5::CommandRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3a5ead86a2476c26428873b534e0e92";
  }

  static const char* value(const ::p5::CommandRobotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3a5ead86a2476c2ULL;
  static const uint64_t static_value2 = 0x6428873b534e0e92ULL;
};

template<class ContainerAllocator>
struct DataType< ::p5::CommandRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p5/CommandRobotResponse";
  }

  static const char* value(const ::p5::CommandRobotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p5::CommandRobotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State next_state\n\
\n\
\n\
================================================================================\n\
MSG: p5/State\n\
int8 location\n\
float64[5] distribution\n\
";
  }

  static const char* value(const ::p5::CommandRobotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p5::CommandRobotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.next_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommandRobotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p5::CommandRobotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p5::CommandRobotResponse_<ContainerAllocator>& v)
  {
    s << indent << "next_state: ";
    s << std::endl;
    Printer< ::p5::State_<ContainerAllocator> >::stream(s, indent + "  ", v.next_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P5_MESSAGE_COMMANDROBOTRESPONSE_H
