// Generated by gencpp from file p5/CommandRobot.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_COMMANDROBOT_H
#define P5_MESSAGE_COMMANDROBOT_H

#include <ros/service_traits.h>


#include <p5/CommandRobotRequest.h>
#include <p5/CommandRobotResponse.h>


namespace p5
{

struct CommandRobot
{

typedef CommandRobotRequest Request;
typedef CommandRobotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CommandRobot
} // namespace p5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p5::CommandRobot > {
  static const char* value()
  {
    return "744a27ef9dbc5d25c1c0c348dc1c1401";
  }

  static const char* value(const ::p5::CommandRobot&) { return value(); }
};

template<>
struct DataType< ::p5::CommandRobot > {
  static const char* value()
  {
    return "p5/CommandRobot";
  }

  static const char* value(const ::p5::CommandRobot&) { return value(); }
};


// service_traits::MD5Sum< ::p5::CommandRobotRequest> should match 
// service_traits::MD5Sum< ::p5::CommandRobot > 
template<>
struct MD5Sum< ::p5::CommandRobotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p5::CommandRobot >::value();
  }
  static const char* value(const ::p5::CommandRobotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::CommandRobotRequest> should match 
// service_traits::DataType< ::p5::CommandRobot > 
template<>
struct DataType< ::p5::CommandRobotRequest>
{
  static const char* value()
  {
    return DataType< ::p5::CommandRobot >::value();
  }
  static const char* value(const ::p5::CommandRobotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p5::CommandRobotResponse> should match 
// service_traits::MD5Sum< ::p5::CommandRobot > 
template<>
struct MD5Sum< ::p5::CommandRobotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p5::CommandRobot >::value();
  }
  static const char* value(const ::p5::CommandRobotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::CommandRobotResponse> should match 
// service_traits::DataType< ::p5::CommandRobot > 
template<>
struct DataType< ::p5::CommandRobotResponse>
{
  static const char* value()
  {
    return DataType< ::p5::CommandRobot >::value();
  }
  static const char* value(const ::p5::CommandRobotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P5_MESSAGE_COMMANDROBOT_H
