// Generated by gencpp from file p5/DetectMetal.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_DETECTMETAL_H
#define P5_MESSAGE_DETECTMETAL_H

#include <ros/service_traits.h>


#include <p5/DetectMetalRequest.h>
#include <p5/DetectMetalResponse.h>


namespace p5
{

struct DetectMetal
{

typedef DetectMetalRequest Request;
typedef DetectMetalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectMetal
} // namespace p5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p5::DetectMetal > {
  static const char* value()
  {
    return "2431cf74dff95a94498ba287cb39d5a3";
  }

  static const char* value(const ::p5::DetectMetal&) { return value(); }
};

template<>
struct DataType< ::p5::DetectMetal > {
  static const char* value()
  {
    return "p5/DetectMetal";
  }

  static const char* value(const ::p5::DetectMetal&) { return value(); }
};


// service_traits::MD5Sum< ::p5::DetectMetalRequest> should match 
// service_traits::MD5Sum< ::p5::DetectMetal > 
template<>
struct MD5Sum< ::p5::DetectMetalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p5::DetectMetal >::value();
  }
  static const char* value(const ::p5::DetectMetalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::DetectMetalRequest> should match 
// service_traits::DataType< ::p5::DetectMetal > 
template<>
struct DataType< ::p5::DetectMetalRequest>
{
  static const char* value()
  {
    return DataType< ::p5::DetectMetal >::value();
  }
  static const char* value(const ::p5::DetectMetalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p5::DetectMetalResponse> should match 
// service_traits::MD5Sum< ::p5::DetectMetal > 
template<>
struct MD5Sum< ::p5::DetectMetalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p5::DetectMetal >::value();
  }
  static const char* value(const ::p5::DetectMetalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::DetectMetalResponse> should match 
// service_traits::DataType< ::p5::DetectMetal > 
template<>
struct DataType< ::p5::DetectMetalResponse>
{
  static const char* value()
  {
    return DataType< ::p5::DetectMetal >::value();
  }
  static const char* value(const ::p5::DetectMetalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P5_MESSAGE_DETECTMETAL_H
