// Generated by gencpp from file p5/DetectMetalResponse.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_DETECTMETALRESPONSE_H
#define P5_MESSAGE_DETECTMETALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace p5
{
template <class ContainerAllocator>
struct DetectMetalResponse_
{
  typedef DetectMetalResponse_<ContainerAllocator> Type;

  DetectMetalResponse_()
    : has_metal(false)
    , distance(0.0)  {
    }
  DetectMetalResponse_(const ContainerAllocator& _alloc)
    : has_metal(false)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _has_metal_type;
  _has_metal_type has_metal;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::p5::DetectMetalResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p5::DetectMetalResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectMetalResponse_

typedef ::p5::DetectMetalResponse_<std::allocator<void> > DetectMetalResponse;

typedef boost::shared_ptr< ::p5::DetectMetalResponse > DetectMetalResponsePtr;
typedef boost::shared_ptr< ::p5::DetectMetalResponse const> DetectMetalResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p5::DetectMetalResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p5::DetectMetalResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p5': ['/home/cs4750/catkin_ws/src/p5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p5::DetectMetalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p5::DetectMetalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::DetectMetalResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::DetectMetalResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::DetectMetalResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::DetectMetalResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p5::DetectMetalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e9e798cf7e51dd17cb11ccb5e6ef8f6";
  }

  static const char* value(const ::p5::DetectMetalResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e9e798cf7e51dd1ULL;
  static const uint64_t static_value2 = 0x7cb11ccb5e6ef8f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::p5::DetectMetalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p5/DetectMetalResponse";
  }

  static const char* value(const ::p5::DetectMetalResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p5::DetectMetalResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool has_metal\n\
float64 distance\n\
\n\
";
  }

  static const char* value(const ::p5::DetectMetalResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p5::DetectMetalResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.has_metal);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectMetalResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p5::DetectMetalResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p5::DetectMetalResponse_<ContainerAllocator>& v)
  {
    s << indent << "has_metal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.has_metal);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P5_MESSAGE_DETECTMETALRESPONSE_H
