// Generated by gencpp from file p5/FollowPath.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_FOLLOWPATH_H
#define P5_MESSAGE_FOLLOWPATH_H

#include <ros/service_traits.h>


#include <p5/FollowPathRequest.h>
#include <p5/FollowPathResponse.h>


namespace p5
{

struct FollowPath
{

typedef FollowPathRequest Request;
typedef FollowPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FollowPath
} // namespace p5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p5::FollowPath > {
  static const char* value()
  {
    return "b58b29f4d3d5430fc9d5efc2f5262786";
  }

  static const char* value(const ::p5::FollowPath&) { return value(); }
};

template<>
struct DataType< ::p5::FollowPath > {
  static const char* value()
  {
    return "p5/FollowPath";
  }

  static const char* value(const ::p5::FollowPath&) { return value(); }
};


// service_traits::MD5Sum< ::p5::FollowPathRequest> should match 
// service_traits::MD5Sum< ::p5::FollowPath > 
template<>
struct MD5Sum< ::p5::FollowPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p5::FollowPath >::value();
  }
  static const char* value(const ::p5::FollowPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::FollowPathRequest> should match 
// service_traits::DataType< ::p5::FollowPath > 
template<>
struct DataType< ::p5::FollowPathRequest>
{
  static const char* value()
  {
    return DataType< ::p5::FollowPath >::value();
  }
  static const char* value(const ::p5::FollowPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p5::FollowPathResponse> should match 
// service_traits::MD5Sum< ::p5::FollowPath > 
template<>
struct MD5Sum< ::p5::FollowPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p5::FollowPath >::value();
  }
  static const char* value(const ::p5::FollowPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::FollowPathResponse> should match 
// service_traits::DataType< ::p5::FollowPath > 
template<>
struct DataType< ::p5::FollowPathResponse>
{
  static const char* value()
  {
    return DataType< ::p5::FollowPath >::value();
  }
  static const char* value(const ::p5::FollowPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P5_MESSAGE_FOLLOWPATH_H
