// Generated by gencpp from file p5/GetPosition.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_GETPOSITION_H
#define P5_MESSAGE_GETPOSITION_H

#include <ros/service_traits.h>


#include <p5/GetPositionRequest.h>
#include <p5/GetPositionResponse.h>


namespace p5
{

struct GetPosition
{

typedef GetPositionRequest Request;
typedef GetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPosition
} // namespace p5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p5::GetPosition > {
  static const char* value()
  {
    return "0825ed03ec91bc18995b0b869f5989a9";
  }

  static const char* value(const ::p5::GetPosition&) { return value(); }
};

template<>
struct DataType< ::p5::GetPosition > {
  static const char* value()
  {
    return "p5/GetPosition";
  }

  static const char* value(const ::p5::GetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::p5::GetPositionRequest> should match 
// service_traits::MD5Sum< ::p5::GetPosition > 
template<>
struct MD5Sum< ::p5::GetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p5::GetPosition >::value();
  }
  static const char* value(const ::p5::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::GetPositionRequest> should match 
// service_traits::DataType< ::p5::GetPosition > 
template<>
struct DataType< ::p5::GetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::p5::GetPosition >::value();
  }
  static const char* value(const ::p5::GetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p5::GetPositionResponse> should match 
// service_traits::MD5Sum< ::p5::GetPosition > 
template<>
struct MD5Sum< ::p5::GetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p5::GetPosition >::value();
  }
  static const char* value(const ::p5::GetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::GetPositionResponse> should match 
// service_traits::DataType< ::p5::GetPosition > 
template<>
struct DataType< ::p5::GetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::p5::GetPosition >::value();
  }
  static const char* value(const ::p5::GetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P5_MESSAGE_GETPOSITION_H
