// Generated by gencpp from file p5/GetTransitionsResponse.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_GETTRANSITIONSRESPONSE_H
#define P5_MESSAGE_GETTRANSITIONSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <p5/ActionOption.h>

namespace p5
{
template <class ContainerAllocator>
struct GetTransitionsResponse_
{
  typedef GetTransitionsResponse_<ContainerAllocator> Type;

  GetTransitionsResponse_()
    : actions()  {
    }
  GetTransitionsResponse_(const ContainerAllocator& _alloc)
    : actions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::p5::ActionOption_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::p5::ActionOption_<ContainerAllocator> >::other >  _actions_type;
  _actions_type actions;





  typedef boost::shared_ptr< ::p5::GetTransitionsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p5::GetTransitionsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetTransitionsResponse_

typedef ::p5::GetTransitionsResponse_<std::allocator<void> > GetTransitionsResponse;

typedef boost::shared_ptr< ::p5::GetTransitionsResponse > GetTransitionsResponsePtr;
typedef boost::shared_ptr< ::p5::GetTransitionsResponse const> GetTransitionsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p5::GetTransitionsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p5::GetTransitionsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p5': ['/home/cs4750/catkin_ws/src/p5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p5::GetTransitionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p5::GetTransitionsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::GetTransitionsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::GetTransitionsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::GetTransitionsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::GetTransitionsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p5::GetTransitionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6675e6895de9e0b5515afd521b48ed56";
  }

  static const char* value(const ::p5::GetTransitionsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6675e6895de9e0b5ULL;
  static const uint64_t static_value2 = 0x515afd521b48ed56ULL;
};

template<class ContainerAllocator>
struct DataType< ::p5::GetTransitionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p5/GetTransitionsResponse";
  }

  static const char* value(const ::p5::GetTransitionsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p5::GetTransitionsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ActionOption[] actions\n\
\n\
\n\
================================================================================\n\
MSG: p5/ActionOption\n\
Action action		# The action can cause any one of the effects\n\
ActionEffect[] effects\n\
\n\
================================================================================\n\
MSG: p5/Action\n\
int8 STOP = -1\n\
int8 SENSE = 0\n\
int8 MOVE1 = 1\n\
int8 MOVE2 = 2\n\
int8 MOVE3 = 3\n\
int8 MOVE4 = 4\n\
int8 MOVE5 = 5\n\
\n\
int8 name\n\
\n\
================================================================================\n\
MSG: p5/ActionEffect\n\
State next_state	# the state this action is transitioning to\n\
float64 probability	# the probability of that transition occurring in this state\n\
float64 reward		# the reward resulting from this transition\n\
\n\
================================================================================\n\
MSG: p5/State\n\
int8 location\n\
float64[5] distribution\n\
";
  }

  static const char* value(const ::p5::GetTransitionsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p5::GetTransitionsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.actions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetTransitionsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p5::GetTransitionsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p5::GetTransitionsResponse_<ContainerAllocator>& v)
  {
    s << indent << "actions[]" << std::endl;
    for (size_t i = 0; i < v.actions.size(); ++i)
    {
      s << indent << "  actions[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::p5::ActionOption_<ContainerAllocator> >::stream(s, indent + "    ", v.actions[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // P5_MESSAGE_GETTRANSITIONSRESPONSE_H
