// Generated by gencpp from file p5/LocateBallResponse.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_LOCATEBALLRESPONSE_H
#define P5_MESSAGE_LOCATEBALLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <p5/State.h>

namespace p5
{
template <class ContainerAllocator>
struct LocateBallResponse_
{
  typedef LocateBallResponse_<ContainerAllocator> Type;

  LocateBallResponse_()
    : final_state()  {
    }
  LocateBallResponse_(const ContainerAllocator& _alloc)
    : final_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::p5::State_<ContainerAllocator>  _final_state_type;
  _final_state_type final_state;





  typedef boost::shared_ptr< ::p5::LocateBallResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p5::LocateBallResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LocateBallResponse_

typedef ::p5::LocateBallResponse_<std::allocator<void> > LocateBallResponse;

typedef boost::shared_ptr< ::p5::LocateBallResponse > LocateBallResponsePtr;
typedef boost::shared_ptr< ::p5::LocateBallResponse const> LocateBallResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p5::LocateBallResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p5::LocateBallResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p5': ['/home/cs4750/catkin_ws/src/p5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p5::LocateBallResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p5::LocateBallResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::LocateBallResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::LocateBallResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::LocateBallResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::LocateBallResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p5::LocateBallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "041775e31ef5aa2b81912ce1c9d22268";
  }

  static const char* value(const ::p5::LocateBallResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x041775e31ef5aa2bULL;
  static const uint64_t static_value2 = 0x81912ce1c9d22268ULL;
};

template<class ContainerAllocator>
struct DataType< ::p5::LocateBallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p5/LocateBallResponse";
  }

  static const char* value(const ::p5::LocateBallResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p5::LocateBallResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "State final_state\n\
\n\
\n\
================================================================================\n\
MSG: p5/State\n\
int8 location\n\
float64[5] distribution\n\
";
  }

  static const char* value(const ::p5::LocateBallResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p5::LocateBallResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LocateBallResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p5::LocateBallResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p5::LocateBallResponse_<ContainerAllocator>& v)
  {
    s << indent << "final_state: ";
    s << std::endl;
    Printer< ::p5::State_<ContainerAllocator> >::stream(s, indent + "  ", v.final_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P5_MESSAGE_LOCATEBALLRESPONSE_H
