// Generated by gencpp from file p5/ModelSenseAction.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_MODELSENSEACTION_H
#define P5_MESSAGE_MODELSENSEACTION_H

#include <ros/service_traits.h>


#include <p5/ModelSenseActionRequest.h>
#include <p5/ModelSenseActionResponse.h>


namespace p5
{

struct ModelSenseAction
{

typedef ModelSenseActionRequest Request;
typedef ModelSenseActionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ModelSenseAction
} // namespace p5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p5::ModelSenseAction > {
  static const char* value()
  {
    return "ccc320a8f7fd9b1f63d549e5acbe4ce5";
  }

  static const char* value(const ::p5::ModelSenseAction&) { return value(); }
};

template<>
struct DataType< ::p5::ModelSenseAction > {
  static const char* value()
  {
    return "p5/ModelSenseAction";
  }

  static const char* value(const ::p5::ModelSenseAction&) { return value(); }
};


// service_traits::MD5Sum< ::p5::ModelSenseActionRequest> should match 
// service_traits::MD5Sum< ::p5::ModelSenseAction > 
template<>
struct MD5Sum< ::p5::ModelSenseActionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p5::ModelSenseAction >::value();
  }
  static const char* value(const ::p5::ModelSenseActionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::ModelSenseActionRequest> should match 
// service_traits::DataType< ::p5::ModelSenseAction > 
template<>
struct DataType< ::p5::ModelSenseActionRequest>
{
  static const char* value()
  {
    return DataType< ::p5::ModelSenseAction >::value();
  }
  static const char* value(const ::p5::ModelSenseActionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p5::ModelSenseActionResponse> should match 
// service_traits::MD5Sum< ::p5::ModelSenseAction > 
template<>
struct MD5Sum< ::p5::ModelSenseActionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p5::ModelSenseAction >::value();
  }
  static const char* value(const ::p5::ModelSenseActionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::ModelSenseActionResponse> should match 
// service_traits::DataType< ::p5::ModelSenseAction > 
template<>
struct DataType< ::p5::ModelSenseActionResponse>
{
  static const char* value()
  {
    return DataType< ::p5::ModelSenseAction >::value();
  }
  static const char* value(const ::p5::ModelSenseActionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P5_MESSAGE_MODELSENSEACTION_H
