// Generated by gencpp from file p5/SetPosition.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_SETPOSITION_H
#define P5_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <p5/SetPositionRequest.h>
#include <p5/SetPositionResponse.h>


namespace p5
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace p5


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p5::SetPosition > {
  static const char* value()
  {
    return "adc15b7ec843fd0b7cee4d793a701b71";
  }

  static const char* value(const ::p5::SetPosition&) { return value(); }
};

template<>
struct DataType< ::p5::SetPosition > {
  static const char* value()
  {
    return "p5/SetPosition";
  }

  static const char* value(const ::p5::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::p5::SetPositionRequest> should match 
// service_traits::MD5Sum< ::p5::SetPosition > 
template<>
struct MD5Sum< ::p5::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p5::SetPosition >::value();
  }
  static const char* value(const ::p5::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::SetPositionRequest> should match 
// service_traits::DataType< ::p5::SetPosition > 
template<>
struct DataType< ::p5::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::p5::SetPosition >::value();
  }
  static const char* value(const ::p5::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p5::SetPositionResponse> should match 
// service_traits::MD5Sum< ::p5::SetPosition > 
template<>
struct MD5Sum< ::p5::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p5::SetPosition >::value();
  }
  static const char* value(const ::p5::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p5::SetPositionResponse> should match 
// service_traits::DataType< ::p5::SetPosition > 
template<>
struct DataType< ::p5::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::p5::SetPosition >::value();
  }
  static const char* value(const ::p5::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P5_MESSAGE_SETPOSITION_H
