// Generated by gencpp from file p5/State.msg
// DO NOT EDIT!


#ifndef P5_MESSAGE_STATE_H
#define P5_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace p5
{
template <class ContainerAllocator>
struct State_
{
  typedef State_<ContainerAllocator> Type;

  State_()
    : location(0)
    , distribution()  {
      distribution.assign(0.0);
  }
  State_(const ContainerAllocator& _alloc)
    : location(0)
    , distribution()  {
  (void)_alloc;
      distribution.assign(0.0);
  }



   typedef int8_t _location_type;
  _location_type location;

   typedef boost::array<double, 5>  _distribution_type;
  _distribution_type distribution;





  typedef boost::shared_ptr< ::p5::State_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p5::State_<ContainerAllocator> const> ConstPtr;

}; // struct State_

typedef ::p5::State_<std::allocator<void> > State;

typedef boost::shared_ptr< ::p5::State > StatePtr;
typedef boost::shared_ptr< ::p5::State const> StateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p5::State_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p5::State_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p5

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p5': ['/home/cs4750/catkin_ws/src/p5/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p5::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p5::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::State_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p5::State_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::State_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p5::State_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p5::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "da5e6c451f1acea84b76d43f796ecca1";
  }

  static const char* value(const ::p5::State_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xda5e6c451f1acea8ULL;
  static const uint64_t static_value2 = 0x4b76d43f796ecca1ULL;
};

template<class ContainerAllocator>
struct DataType< ::p5::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p5/State";
  }

  static const char* value(const ::p5::State_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p5::State_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 location\n\
float64[5] distribution\n\
";
  }

  static const char* value(const ::p5::State_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p5::State_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
      stream.next(m.distribution);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct State_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p5::State_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p5::State_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    Printer<int8_t>::stream(s, indent + "  ", v.location);
    s << indent << "distribution[]" << std::endl;
    for (size_t i = 0; i < v.distribution.size(); ++i)
    {
      s << indent << "  distribution[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.distribution[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // P5_MESSAGE_STATE_H
