// Generated by gencpp from file p2/Differential.msg
// DO NOT EDIT!


#ifndef P2_MESSAGE_DIFFERENTIAL_H
#define P2_MESSAGE_DIFFERENTIAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace p2
{
template <class ContainerAllocator>
struct Differential_
{
  typedef Differential_<ContainerAllocator> Type;

  Differential_()
    : left_vel(0.0)
    , right_vel(0.0)  {
    }
  Differential_(const ContainerAllocator& _alloc)
    : left_vel(0.0)
    , right_vel(0.0)  {
  (void)_alloc;
    }



   typedef double _left_vel_type;
  _left_vel_type left_vel;

   typedef double _right_vel_type;
  _right_vel_type right_vel;





  typedef boost::shared_ptr< ::p2::Differential_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p2::Differential_<ContainerAllocator> const> ConstPtr;

}; // struct Differential_

typedef ::p2::Differential_<std::allocator<void> > Differential;

typedef boost::shared_ptr< ::p2::Differential > DifferentialPtr;
typedef boost::shared_ptr< ::p2::Differential const> DifferentialConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p2::Differential_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p2::Differential_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p2

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'p2': ['/home/cs4750/catkin_ws/src/p2/msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p2::Differential_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p2::Differential_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p2::Differential_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p2::Differential_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p2::Differential_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p2::Differential_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p2::Differential_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6276768e5df1d6b78b96e63931fb03fc";
  }

  static const char* value(const ::p2::Differential_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6276768e5df1d6b7ULL;
  static const uint64_t static_value2 = 0x8b96e63931fb03fcULL;
};

template<class ContainerAllocator>
struct DataType< ::p2::Differential_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p2/Differential";
  }

  static const char* value(const ::p2::Differential_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p2::Differential_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 left_vel\n\
float64 right_vel\n\
";
  }

  static const char* value(const ::p2::Differential_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p2::Differential_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_vel);
      stream.next(m.right_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Differential_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p2::Differential_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p2::Differential_<ContainerAllocator>& v)
  {
    s << indent << "left_vel: ";
    Printer<double>::stream(s, indent + "  ", v.left_vel);
    s << indent << "right_vel: ";
    Printer<double>::stream(s, indent + "  ", v.right_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P2_MESSAGE_DIFFERENTIAL_H
