// Generated by gencpp from file p3/JacStringResponse.msg
// DO NOT EDIT!


#ifndef P3_MESSAGE_JACSTRINGRESPONSE_H
#define P3_MESSAGE_JACSTRINGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace p3
{
template <class ContainerAllocator>
struct JacStringResponse_
{
  typedef JacStringResponse_<ContainerAllocator> Type;

  JacStringResponse_()
    : jacobian()  {
    }
  JacStringResponse_(const ContainerAllocator& _alloc)
    : jacobian(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _jacobian_type;
  _jacobian_type jacobian;





  typedef boost::shared_ptr< ::p3::JacStringResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p3::JacStringResponse_<ContainerAllocator> const> ConstPtr;

}; // struct JacStringResponse_

typedef ::p3::JacStringResponse_<std::allocator<void> > JacStringResponse;

typedef boost::shared_ptr< ::p3::JacStringResponse > JacStringResponsePtr;
typedef boost::shared_ptr< ::p3::JacStringResponse const> JacStringResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p3::JacStringResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p3::JacStringResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'p3': ['/home/cs4750/catkin_ws/src/p3/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p3::JacStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p3::JacStringResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::JacStringResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::JacStringResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::JacStringResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::JacStringResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p3::JacStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e10611babd37b65962dbe9c28cedb978";
  }

  static const char* value(const ::p3::JacStringResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe10611babd37b659ULL;
  static const uint64_t static_value2 = 0x62dbe9c28cedb978ULL;
};

template<class ContainerAllocator>
struct DataType< ::p3::JacStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p3/JacStringResponse";
  }

  static const char* value(const ::p3::JacStringResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p3::JacStringResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string jacobian\n\
\n\
";
  }

  static const char* value(const ::p3::JacStringResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p3::JacStringResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jacobian);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JacStringResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p3::JacStringResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p3::JacStringResponse_<ContainerAllocator>& v)
  {
    s << indent << "jacobian: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.jacobian);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P3_MESSAGE_JACSTRINGRESPONSE_H
