// Generated by gencpp from file p3/JacString.msg
// DO NOT EDIT!


#ifndef P3_MESSAGE_JACSTRING_H
#define P3_MESSAGE_JACSTRING_H

#include <ros/service_traits.h>


#include <p3/JacStringRequest.h>
#include <p3/JacStringResponse.h>


namespace p3
{

struct JacString
{

typedef JacStringRequest Request;
typedef JacStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JacString
} // namespace p3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p3::JacString > {
  static const char* value()
  {
    return "e10611babd37b65962dbe9c28cedb978";
  }

  static const char* value(const ::p3::JacString&) { return value(); }
};

template<>
struct DataType< ::p3::JacString > {
  static const char* value()
  {
    return "p3/JacString";
  }

  static const char* value(const ::p3::JacString&) { return value(); }
};


// service_traits::MD5Sum< ::p3::JacStringRequest> should match 
// service_traits::MD5Sum< ::p3::JacString > 
template<>
struct MD5Sum< ::p3::JacStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p3::JacString >::value();
  }
  static const char* value(const ::p3::JacStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p3::JacStringRequest> should match 
// service_traits::DataType< ::p3::JacString > 
template<>
struct DataType< ::p3::JacStringRequest>
{
  static const char* value()
  {
    return DataType< ::p3::JacString >::value();
  }
  static const char* value(const ::p3::JacStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p3::JacStringResponse> should match 
// service_traits::MD5Sum< ::p3::JacString > 
template<>
struct MD5Sum< ::p3::JacStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p3::JacString >::value();
  }
  static const char* value(const ::p3::JacStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p3::JacStringResponse> should match 
// service_traits::DataType< ::p3::JacString > 
template<>
struct DataType< ::p3::JacStringResponse>
{
  static const char* value()
  {
    return DataType< ::p3::JacString >::value();
  }
  static const char* value(const ::p3::JacStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P3_MESSAGE_JACSTRING_H
