// Generated by gencpp from file p3/JointAngles.msg
// DO NOT EDIT!


#ifndef P3_MESSAGE_JOINTANGLES_H
#define P3_MESSAGE_JOINTANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace p3
{
template <class ContainerAllocator>
struct JointAngles_
{
  typedef JointAngles_<ContainerAllocator> Type;

  JointAngles_()
    : angles()  {
      angles.assign(0.0);
  }
  JointAngles_(const ContainerAllocator& _alloc)
    : angles()  {
  (void)_alloc;
      angles.assign(0.0);
  }



   typedef boost::array<double, 5>  _angles_type;
  _angles_type angles;





  typedef boost::shared_ptr< ::p3::JointAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p3::JointAngles_<ContainerAllocator> const> ConstPtr;

}; // struct JointAngles_

typedef ::p3::JointAngles_<std::allocator<void> > JointAngles;

typedef boost::shared_ptr< ::p3::JointAngles > JointAnglesPtr;
typedef boost::shared_ptr< ::p3::JointAngles const> JointAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p3::JointAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p3::JointAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'p3': ['/home/cs4750/catkin_ws/src/p3/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p3::JointAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p3::JointAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::JointAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::JointAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::JointAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::JointAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p3::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "266f4497ea1dcf85e7f9989383bff1ae";
  }

  static const char* value(const ::p3::JointAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x266f4497ea1dcf85ULL;
  static const uint64_t static_value2 = 0xe7f9989383bff1aeULL;
};

template<class ContainerAllocator>
struct DataType< ::p3::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p3/JointAngles";
  }

  static const char* value(const ::p3::JointAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p3::JointAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[5] angles\n\
";
  }

  static const char* value(const ::p3::JointAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p3::JointAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p3::JointAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p3::JointAngles_<ContainerAllocator>& v)
  {
    s << indent << "angles[]" << std::endl;
    for (size_t i = 0; i < v.angles.size(); ++i)
    {
      s << indent << "  angles[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.angles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // P3_MESSAGE_JOINTANGLES_H
