// Generated by gencpp from file p3/Problem3aRequest.msg
// DO NOT EDIT!


#ifndef P3_MESSAGE_PROBLEM3AREQUEST_H
#define P3_MESSAGE_PROBLEM3AREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace p3
{
template <class ContainerAllocator>
struct Problem3aRequest_
{
  typedef Problem3aRequest_<ContainerAllocator> Type;

  Problem3aRequest_()
    : position()  {
    }
  Problem3aRequest_(const ContainerAllocator& _alloc)
    : position(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::p3::Problem3aRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p3::Problem3aRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Problem3aRequest_

typedef ::p3::Problem3aRequest_<std::allocator<void> > Problem3aRequest;

typedef boost::shared_ptr< ::p3::Problem3aRequest > Problem3aRequestPtr;
typedef boost::shared_ptr< ::p3::Problem3aRequest const> Problem3aRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p3::Problem3aRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p3::Problem3aRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'p3': ['/home/cs4750/catkin_ws/src/p3/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p3::Problem3aRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p3::Problem3aRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::Problem3aRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::Problem3aRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::Problem3aRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::Problem3aRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p3::Problem3aRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e7bb0ef028c744b081acdc57743b11d8";
  }

  static const char* value(const ::p3::Problem3aRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe7bb0ef028c744b0ULL;
  static const uint64_t static_value2 = 0x81acdc57743b11d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::p3::Problem3aRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p3/Problem3aRequest";
  }

  static const char* value(const ::p3::Problem3aRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p3::Problem3aRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point position\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::p3::Problem3aRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p3::Problem3aRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Problem3aRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p3::Problem3aRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p3::Problem3aRequest_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P3_MESSAGE_PROBLEM3AREQUEST_H
