// Generated by gencpp from file p3/Problem1Response.msg
// DO NOT EDIT!


#ifndef P3_MESSAGE_PROBLEM1RESPONSE_H
#define P3_MESSAGE_PROBLEM1RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <p3/PointArray.h>

namespace p3
{
template <class ContainerAllocator>
struct Problem1Response_
{
  typedef Problem1Response_<ContainerAllocator> Type;

  Problem1Response_()
    : points()  {
    }
  Problem1Response_(const ContainerAllocator& _alloc)
    : points(_alloc)  {
  (void)_alloc;
    }



   typedef  ::p3::PointArray_<ContainerAllocator>  _points_type;
  _points_type points;





  typedef boost::shared_ptr< ::p3::Problem1Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p3::Problem1Response_<ContainerAllocator> const> ConstPtr;

}; // struct Problem1Response_

typedef ::p3::Problem1Response_<std::allocator<void> > Problem1Response;

typedef boost::shared_ptr< ::p3::Problem1Response > Problem1ResponsePtr;
typedef boost::shared_ptr< ::p3::Problem1Response const> Problem1ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p3::Problem1Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p3::Problem1Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'p3': ['/home/cs4750/catkin_ws/src/p3/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p3::Problem1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p3::Problem1Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::Problem1Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::Problem1Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::Problem1Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::Problem1Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p3::Problem1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f7b43fb4c3dc044f1ecb1f843f952947";
  }

  static const char* value(const ::p3::Problem1Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf7b43fb4c3dc044fULL;
  static const uint64_t static_value2 = 0x1ecb1f843f952947ULL;
};

template<class ContainerAllocator>
struct DataType< ::p3::Problem1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p3/Problem1Response";
  }

  static const char* value(const ::p3::Problem1Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p3::Problem1Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "PointArray points\n\
\n\
\n\
================================================================================\n\
MSG: p3/PointArray\n\
geometry_msgs/Point[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::p3::Problem1Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p3::Problem1Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.points);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Problem1Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p3::Problem1Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p3::Problem1Response_<ContainerAllocator>& v)
  {
    s << indent << "points: ";
    s << std::endl;
    Printer< ::p3::PointArray_<ContainerAllocator> >::stream(s, indent + "  ", v.points);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P3_MESSAGE_PROBLEM1RESPONSE_H
