// Generated by gencpp from file p3/Problem2.msg
// DO NOT EDIT!


#ifndef P3_MESSAGE_PROBLEM2_H
#define P3_MESSAGE_PROBLEM2_H

#include <ros/service_traits.h>


#include <p3/Problem2Request.h>
#include <p3/Problem2Response.h>


namespace p3
{

struct Problem2
{

typedef Problem2Request Request;
typedef Problem2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Problem2
} // namespace p3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p3::Problem2 > {
  static const char* value()
  {
    return "4aaf0985c732d731cb605701418dce69";
  }

  static const char* value(const ::p3::Problem2&) { return value(); }
};

template<>
struct DataType< ::p3::Problem2 > {
  static const char* value()
  {
    return "p3/Problem2";
  }

  static const char* value(const ::p3::Problem2&) { return value(); }
};


// service_traits::MD5Sum< ::p3::Problem2Request> should match 
// service_traits::MD5Sum< ::p3::Problem2 > 
template<>
struct MD5Sum< ::p3::Problem2Request>
{
  static const char* value()
  {
    return MD5Sum< ::p3::Problem2 >::value();
  }
  static const char* value(const ::p3::Problem2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::p3::Problem2Request> should match 
// service_traits::DataType< ::p3::Problem2 > 
template<>
struct DataType< ::p3::Problem2Request>
{
  static const char* value()
  {
    return DataType< ::p3::Problem2 >::value();
  }
  static const char* value(const ::p3::Problem2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p3::Problem2Response> should match 
// service_traits::MD5Sum< ::p3::Problem2 > 
template<>
struct MD5Sum< ::p3::Problem2Response>
{
  static const char* value()
  {
    return MD5Sum< ::p3::Problem2 >::value();
  }
  static const char* value(const ::p3::Problem2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::p3::Problem2Response> should match 
// service_traits::DataType< ::p3::Problem2 > 
template<>
struct DataType< ::p3::Problem2Response>
{
  static const char* value()
  {
    return DataType< ::p3::Problem2 >::value();
  }
  static const char* value(const ::p3::Problem2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P3_MESSAGE_PROBLEM2_H
