// Generated by gencpp from file p3/Problem2Response.msg
// DO NOT EDIT!


#ifndef P3_MESSAGE_PROBLEM2RESPONSE_H
#define P3_MESSAGE_PROBLEM2RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Float64MultiArray.h>

namespace p3
{
template <class ContainerAllocator>
struct Problem2Response_
{
  typedef Problem2Response_<ContainerAllocator> Type;

  Problem2Response_()
    : jac()  {
    }
  Problem2Response_(const ContainerAllocator& _alloc)
    : jac(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _jac_type;
  _jac_type jac;





  typedef boost::shared_ptr< ::p3::Problem2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p3::Problem2Response_<ContainerAllocator> const> ConstPtr;

}; // struct Problem2Response_

typedef ::p3::Problem2Response_<std::allocator<void> > Problem2Response;

typedef boost::shared_ptr< ::p3::Problem2Response > Problem2ResponsePtr;
typedef boost::shared_ptr< ::p3::Problem2Response const> Problem2ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p3::Problem2Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p3::Problem2Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p3

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'p3': ['/home/cs4750/catkin_ws/src/p3/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p3::Problem2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p3::Problem2Response_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::Problem2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p3::Problem2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::Problem2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p3::Problem2Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p3::Problem2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c429c34eb4f5e0a5ed9c42c5d74ee94a";
  }

  static const char* value(const ::p3::Problem2Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc429c34eb4f5e0a5ULL;
  static const uint64_t static_value2 = 0xed9c42c5d74ee94aULL;
};

template<class ContainerAllocator>
struct DataType< ::p3::Problem2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p3/Problem2Response";
  }

  static const char* value(const ::p3::Problem2Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p3::Problem2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Float64MultiArray jac\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Float64MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
float64[]         data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::p3::Problem2Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p3::Problem2Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.jac);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Problem2Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p3::Problem2Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p3::Problem2Response_<ContainerAllocator>& v)
  {
    s << indent << "jac: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.jac);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P3_MESSAGE_PROBLEM2RESPONSE_H
