// Generated by gencpp from file p3/Problem1.msg
// DO NOT EDIT!


#ifndef P3_MESSAGE_PROBLEM1_H
#define P3_MESSAGE_PROBLEM1_H

#include <ros/service_traits.h>


#include <p3/Problem1Request.h>
#include <p3/Problem1Response.h>


namespace p3
{

struct Problem1
{

typedef Problem1Request Request;
typedef Problem1Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Problem1
} // namespace p3


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p3::Problem1 > {
  static const char* value()
  {
    return "0f43d6b0b523860f6489ab1d8e5a3c26";
  }

  static const char* value(const ::p3::Problem1&) { return value(); }
};

template<>
struct DataType< ::p3::Problem1 > {
  static const char* value()
  {
    return "p3/Problem1";
  }

  static const char* value(const ::p3::Problem1&) { return value(); }
};


// service_traits::MD5Sum< ::p3::Problem1Request> should match 
// service_traits::MD5Sum< ::p3::Problem1 > 
template<>
struct MD5Sum< ::p3::Problem1Request>
{
  static const char* value()
  {
    return MD5Sum< ::p3::Problem1 >::value();
  }
  static const char* value(const ::p3::Problem1Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::p3::Problem1Request> should match 
// service_traits::DataType< ::p3::Problem1 > 
template<>
struct DataType< ::p3::Problem1Request>
{
  static const char* value()
  {
    return DataType< ::p3::Problem1 >::value();
  }
  static const char* value(const ::p3::Problem1Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p3::Problem1Response> should match 
// service_traits::MD5Sum< ::p3::Problem1 > 
template<>
struct MD5Sum< ::p3::Problem1Response>
{
  static const char* value()
  {
    return MD5Sum< ::p3::Problem1 >::value();
  }
  static const char* value(const ::p3::Problem1Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::p3::Problem1Response> should match 
// service_traits::DataType< ::p3::Problem1 > 
template<>
struct DataType< ::p3::Problem1Response>
{
  static const char* value()
  {
    return DataType< ::p3::Problem1 >::value();
  }
  static const char* value(const ::p3::Problem1Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P3_MESSAGE_PROBLEM1_H
