build = "cd ../.. && catkin build && cp src/p5/libv_repExtRosInterface.so ~/vrep/"
structure_paths = [
  "src/problem1.py",
  "src/problem2.py",
  "src/problem3.py",
  "src/problem4.py",
  "src/problem5a.py",
  "src/problem5b.py",
  "launch/visualize.launch",
  "launch/problem4.launch",
  "launch/problem5a.launch",
  "launch/problem5b.launch"
]
copy_paths = [
  "config.toml",
  "libv_repExtRosInterface.so",
  "scenes/p5.ttt",
  "bin/action_server.so",
  "bin/block_sensors.so",
  "bin/drive.py",
  "bin/interpolate_server.so",
  "bin/problem1_solution.so",
  "bin/problem2_solution.so",
  "bin/problem3_solution.so",
  "bin/problem4_solution.so",
  "bin/problem5a_solution.so",
  "bin/problem5b_solution.so",
  "bin/pure_pursuit.so",
  "bin/randomize_blocks.so",
  "bin/so_runner",
  "bin/start_vrep",
  "bin/transition_server.so",
  "bin/visualizer.so",
  "launch/main.launch",
  "launch/visualize_solution.launch",
  "launch/problem4_solution.launch",
  "launch/problem5a_solution.launch",
  "launch/problem5b_solution.launch",
  "msg/Action.msg",
  "msg/ActionEffect.msg",
  "msg/ActionOption.msg",
  "msg/State.msg",
  "srv/ChooseAction.srv",
  "srv/CommandRobot.srv",
  "srv/DetectMetal.srv",
  "srv/GetPosition.srv",
  "srv/InterpolatePath.srv",
  "srv/ModelSenseAction.srv",
  "srv/SetPosition.srv",
  "srv/ClosestPointPath.srv",
  "srv/ComputeEntropy.srv",
  "srv/FollowPath.srv",
  "srv/GetTransitions.srv",
  "srv/LocateBall.srv",
  "srv/SenseBall.srv"
]
exclude_paths = [
  "libv_repExtRosInterface.so",
  "scenes/p5.ttt"
]
