// Generated by gencpp from file p4/ClosestPointPath.msg
// DO NOT EDIT!


#ifndef P4_MESSAGE_CLOSESTPOINTPATH_H
#define P4_MESSAGE_CLOSESTPOINTPATH_H

#include <ros/service_traits.h>


#include <p4/ClosestPointPathRequest.h>
#include <p4/ClosestPointPathResponse.h>


namespace p4
{

struct ClosestPointPath
{

typedef ClosestPointPathRequest Request;
typedef ClosestPointPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ClosestPointPath
} // namespace p4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p4::ClosestPointPath > {
  static const char* value()
  {
    return "a4eb7978da311d6bb271e96cc9f6a8e7";
  }

  static const char* value(const ::p4::ClosestPointPath&) { return value(); }
};

template<>
struct DataType< ::p4::ClosestPointPath > {
  static const char* value()
  {
    return "p4/ClosestPointPath";
  }

  static const char* value(const ::p4::ClosestPointPath&) { return value(); }
};


// service_traits::MD5Sum< ::p4::ClosestPointPathRequest> should match 
// service_traits::MD5Sum< ::p4::ClosestPointPath > 
template<>
struct MD5Sum< ::p4::ClosestPointPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p4::ClosestPointPath >::value();
  }
  static const char* value(const ::p4::ClosestPointPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::ClosestPointPathRequest> should match 
// service_traits::DataType< ::p4::ClosestPointPath > 
template<>
struct DataType< ::p4::ClosestPointPathRequest>
{
  static const char* value()
  {
    return DataType< ::p4::ClosestPointPath >::value();
  }
  static const char* value(const ::p4::ClosestPointPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p4::ClosestPointPathResponse> should match 
// service_traits::MD5Sum< ::p4::ClosestPointPath > 
template<>
struct MD5Sum< ::p4::ClosestPointPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p4::ClosestPointPath >::value();
  }
  static const char* value(const ::p4::ClosestPointPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::ClosestPointPathResponse> should match 
// service_traits::DataType< ::p4::ClosestPointPath > 
template<>
struct DataType< ::p4::ClosestPointPathResponse>
{
  static const char* value()
  {
    return DataType< ::p4::ClosestPointPath >::value();
  }
  static const char* value(const ::p4::ClosestPointPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P4_MESSAGE_CLOSESTPOINTPATH_H
