// Generated by gencpp from file p4/FindPath.msg
// DO NOT EDIT!


#ifndef P4_MESSAGE_FINDPATH_H
#define P4_MESSAGE_FINDPATH_H

#include <ros/service_traits.h>


#include <p4/FindPathRequest.h>
#include <p4/FindPathResponse.h>


namespace p4
{

struct FindPath
{

typedef FindPathRequest Request;
typedef FindPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct FindPath
} // namespace p4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p4::FindPath > {
  static const char* value()
  {
    return "7a0021ee1a6c7c0d91e54fbc04ac10ec";
  }

  static const char* value(const ::p4::FindPath&) { return value(); }
};

template<>
struct DataType< ::p4::FindPath > {
  static const char* value()
  {
    return "p4/FindPath";
  }

  static const char* value(const ::p4::FindPath&) { return value(); }
};


// service_traits::MD5Sum< ::p4::FindPathRequest> should match 
// service_traits::MD5Sum< ::p4::FindPath > 
template<>
struct MD5Sum< ::p4::FindPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p4::FindPath >::value();
  }
  static const char* value(const ::p4::FindPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::FindPathRequest> should match 
// service_traits::DataType< ::p4::FindPath > 
template<>
struct DataType< ::p4::FindPathRequest>
{
  static const char* value()
  {
    return DataType< ::p4::FindPath >::value();
  }
  static const char* value(const ::p4::FindPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p4::FindPathResponse> should match 
// service_traits::MD5Sum< ::p4::FindPath > 
template<>
struct MD5Sum< ::p4::FindPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p4::FindPath >::value();
  }
  static const char* value(const ::p4::FindPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::FindPathResponse> should match 
// service_traits::DataType< ::p4::FindPath > 
template<>
struct DataType< ::p4::FindPathResponse>
{
  static const char* value()
  {
    return DataType< ::p4::FindPath >::value();
  }
  static const char* value(const ::p4::FindPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P4_MESSAGE_FINDPATH_H
