// Generated by gencpp from file p4/InterpolatePathRequest.msg
// DO NOT EDIT!


#ifndef P4_MESSAGE_INTERPOLATEPATHREQUEST_H
#define P4_MESSAGE_INTERPOLATEPATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <std_msgs/Float32.h>

namespace p4
{
template <class ContainerAllocator>
struct InterpolatePathRequest_
{
  typedef InterpolatePathRequest_<ContainerAllocator> Type;

  InterpolatePathRequest_()
    : path()
    , distance()  {
    }
  InterpolatePathRequest_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , distance(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Point_<ContainerAllocator> >::other >  _path_type;
  _path_type path;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::p4::InterpolatePathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::p4::InterpolatePathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InterpolatePathRequest_

typedef ::p4::InterpolatePathRequest_<std::allocator<void> > InterpolatePathRequest;

typedef boost::shared_ptr< ::p4::InterpolatePathRequest > InterpolatePathRequestPtr;
typedef boost::shared_ptr< ::p4::InterpolatePathRequest const> InterpolatePathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::p4::InterpolatePathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::p4::InterpolatePathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace p4

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'p4': ['/home/cs4750/catkin_ws/src/p4/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::p4::InterpolatePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::p4::InterpolatePathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p4::InterpolatePathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::p4::InterpolatePathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p4::InterpolatePathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::p4::InterpolatePathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::p4::InterpolatePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ebde1d308354c5dd038dc090c6426ca";
  }

  static const char* value(const ::p4::InterpolatePathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ebde1d308354c5dULL;
  static const uint64_t static_value2 = 0xd038dc090c6426caULL;
};

template<class ContainerAllocator>
struct DataType< ::p4::InterpolatePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "p4/InterpolatePathRequest";
  }

  static const char* value(const ::p4::InterpolatePathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::p4::InterpolatePathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Point[] path\n\
std_msgs/Float32 distance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::p4::InterpolatePathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::p4::InterpolatePathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InterpolatePathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::p4::InterpolatePathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::p4::InterpolatePathRequest_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
    s << indent << "distance: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // P4_MESSAGE_INTERPOLATEPATHREQUEST_H
