// Generated by gencpp from file p4/InterpolatePath.msg
// DO NOT EDIT!


#ifndef P4_MESSAGE_INTERPOLATEPATH_H
#define P4_MESSAGE_INTERPOLATEPATH_H

#include <ros/service_traits.h>


#include <p4/InterpolatePathRequest.h>
#include <p4/InterpolatePathResponse.h>


namespace p4
{

struct InterpolatePath
{

typedef InterpolatePathRequest Request;
typedef InterpolatePathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InterpolatePath
} // namespace p4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p4::InterpolatePath > {
  static const char* value()
  {
    return "8c3e2084abc80e147089171826a07fe3";
  }

  static const char* value(const ::p4::InterpolatePath&) { return value(); }
};

template<>
struct DataType< ::p4::InterpolatePath > {
  static const char* value()
  {
    return "p4/InterpolatePath";
  }

  static const char* value(const ::p4::InterpolatePath&) { return value(); }
};


// service_traits::MD5Sum< ::p4::InterpolatePathRequest> should match 
// service_traits::MD5Sum< ::p4::InterpolatePath > 
template<>
struct MD5Sum< ::p4::InterpolatePathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p4::InterpolatePath >::value();
  }
  static const char* value(const ::p4::InterpolatePathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::InterpolatePathRequest> should match 
// service_traits::DataType< ::p4::InterpolatePath > 
template<>
struct DataType< ::p4::InterpolatePathRequest>
{
  static const char* value()
  {
    return DataType< ::p4::InterpolatePath >::value();
  }
  static const char* value(const ::p4::InterpolatePathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p4::InterpolatePathResponse> should match 
// service_traits::MD5Sum< ::p4::InterpolatePath > 
template<>
struct MD5Sum< ::p4::InterpolatePathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p4::InterpolatePath >::value();
  }
  static const char* value(const ::p4::InterpolatePathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::InterpolatePathResponse> should match 
// service_traits::DataType< ::p4::InterpolatePath > 
template<>
struct DataType< ::p4::InterpolatePathResponse>
{
  static const char* value()
  {
    return DataType< ::p4::InterpolatePath >::value();
  }
  static const char* value(const ::p4::InterpolatePathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P4_MESSAGE_INTERPOLATEPATH_H
