// Generated by gencpp from file p4/ReachPos.msg
// DO NOT EDIT!


#ifndef P4_MESSAGE_REACHPOS_H
#define P4_MESSAGE_REACHPOS_H

#include <ros/service_traits.h>


#include <p4/ReachPosRequest.h>
#include <p4/ReachPosResponse.h>


namespace p4
{

struct ReachPos
{

typedef ReachPosRequest Request;
typedef ReachPosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReachPos
} // namespace p4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p4::ReachPos > {
  static const char* value()
  {
    return "f6223c7abdc4b623d217c01366131467";
  }

  static const char* value(const ::p4::ReachPos&) { return value(); }
};

template<>
struct DataType< ::p4::ReachPos > {
  static const char* value()
  {
    return "p4/ReachPos";
  }

  static const char* value(const ::p4::ReachPos&) { return value(); }
};


// service_traits::MD5Sum< ::p4::ReachPosRequest> should match 
// service_traits::MD5Sum< ::p4::ReachPos > 
template<>
struct MD5Sum< ::p4::ReachPosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p4::ReachPos >::value();
  }
  static const char* value(const ::p4::ReachPosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::ReachPosRequest> should match 
// service_traits::DataType< ::p4::ReachPos > 
template<>
struct DataType< ::p4::ReachPosRequest>
{
  static const char* value()
  {
    return DataType< ::p4::ReachPos >::value();
  }
  static const char* value(const ::p4::ReachPosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p4::ReachPosResponse> should match 
// service_traits::MD5Sum< ::p4::ReachPos > 
template<>
struct MD5Sum< ::p4::ReachPosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p4::ReachPos >::value();
  }
  static const char* value(const ::p4::ReachPosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::ReachPosResponse> should match 
// service_traits::DataType< ::p4::ReachPos > 
template<>
struct DataType< ::p4::ReachPosResponse>
{
  static const char* value()
  {
    return DataType< ::p4::ReachPos >::value();
  }
  static const char* value(const ::p4::ReachPosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P4_MESSAGE_REACHPOS_H
