// Generated by gencpp from file p4/SetPosition.msg
// DO NOT EDIT!


#ifndef P4_MESSAGE_SETPOSITION_H
#define P4_MESSAGE_SETPOSITION_H

#include <ros/service_traits.h>


#include <p4/SetPositionRequest.h>
#include <p4/SetPositionResponse.h>


namespace p4
{

struct SetPosition
{

typedef SetPositionRequest Request;
typedef SetPositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPosition
} // namespace p4


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::p4::SetPosition > {
  static const char* value()
  {
    return "adc15b7ec843fd0b7cee4d793a701b71";
  }

  static const char* value(const ::p4::SetPosition&) { return value(); }
};

template<>
struct DataType< ::p4::SetPosition > {
  static const char* value()
  {
    return "p4/SetPosition";
  }

  static const char* value(const ::p4::SetPosition&) { return value(); }
};


// service_traits::MD5Sum< ::p4::SetPositionRequest> should match 
// service_traits::MD5Sum< ::p4::SetPosition > 
template<>
struct MD5Sum< ::p4::SetPositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::p4::SetPosition >::value();
  }
  static const char* value(const ::p4::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::SetPositionRequest> should match 
// service_traits::DataType< ::p4::SetPosition > 
template<>
struct DataType< ::p4::SetPositionRequest>
{
  static const char* value()
  {
    return DataType< ::p4::SetPosition >::value();
  }
  static const char* value(const ::p4::SetPositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::p4::SetPositionResponse> should match 
// service_traits::MD5Sum< ::p4::SetPosition > 
template<>
struct MD5Sum< ::p4::SetPositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::p4::SetPosition >::value();
  }
  static const char* value(const ::p4::SetPositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::p4::SetPositionResponse> should match 
// service_traits::DataType< ::p4::SetPosition > 
template<>
struct DataType< ::p4::SetPositionResponse>
{
  static const char* value()
  {
    return DataType< ::p4::SetPosition >::value();
  }
  static const char* value(const ::p4::SetPositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // P4_MESSAGE_SETPOSITION_H
